# Generated by Django 4.1.6 on 2023-02-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_created_alter_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
