# Generated by Django 4.1.6 on 2023-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('sender', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('detail', models.TextField()),
            ],
        ),
    ]
